version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      prod-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
